[package]
name = "a04_no_std_main_start_part2"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true

[[bin]]
name = "a04_no_std_main_start_part2"
path = "src/main.rs"
