[target.'aarch64-apple-darwin']
rustflags = [
    "-C", "link-arg=-Wl,-e,_start",
    "-C", "panic=abort"
]

[target.'x86_64-unknown-linux-gnu']
rustflags = [
    "-C", "link-arg=-nostartfiles",
    "-C", "panic=abort"
]

# For bare-metal ARM targets
[target.'aarch64-unknown-none']
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "panic=abort"
]
