[build]
rustflags = ["-Z", "threads=8"]
target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "panic=abort",
    "-C", "opt-level=z",
    "-C", "link-args=-nostartfiles -nostdlib",
]
